djangolecture/urls.py
from django.contrib import admin
from django.urls import path, include
from myapp.views import hello_world

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', hello_world),
    path('myapp/', include("myapp.urls")),
    path('todo/', include("todo.urls"))
]

myapp/urls.py
from django.urls import path
from .views import FirstView, SecondView

urlpatterns = [
    path('first/', FirstView.as_view()),
    path('second/', SecondView.as_view())
]

todo/urls.py
from django.urls import path
from .apis import TodoCreateAPI, TodoDetailAPI, TodoUpdateAPI, TodoDeleteAPI
from .views import TodoCreateView, TodoListView, TodoDetailView, TodoUpdateView

app_name = "todo"

urlpatterns = [
    #API
    path('api/create/',TodoCreateAPI.as_view()),
    path('api/detail/<int:pk>',TodoDetailAPI.as_view()),
    path('api/update/<int:pk>',TodoUpdateAPI.as_view()),
    path('api/delete/<int:pk>',TodoDeleteAPI.as_view()),

    #VIEW
    path('create/', TodoCreateView.as_view()),
    path('list/', TodoListView.as_view(), name = "list"),
    path('detail/<int:pk>', TodoDetailView.as_view(), name="detail"),
    path('update/<int:pk>', TodoUpdateView.as_view(), name="update")
]

users/urls.py
from django.urls import path
from .apis import SignupAPI, LoginAPI
from .views import SignupView, LoginView

app_name = 'users'

urlpatterns=[
    path("api/signup/", SignupAPI.as_view()),
    path("signup/", SignupView.as_view()),

    path("api/login/", LoginAPI.as_view()),
    path("login/", LoginView.as_view()),
]

myapp/models.py
from django.db import models

# Create your models here.

todo/models.py
from django.db import models

# Create your models here.

class Todo(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField(blank=True)
    created = models.DateTimeField(auto_now_add=True)
    complete = models.BooleanField(default=False)
    important = models.BooleanField(default=False)

    def __str__(self):
        return self.title

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.utils import timezone


# Create your models here.

class UserManager(BaseUserManager):
    def _create_user(self, phone_number, password, is_staff, is_superuser, **extra_fields):
        if not phone_number:
            raise ValueError("user must have phone_number")
        now = timezone.now()
        user = self.model(
            phone_number=phone_number,
            is_active=is_staff,
            is_superuser=is_superuser,
            last_login=now,
            date_joined=now,
            **extra_fields
        )
        if password:
            user.set_password(password) #암호화

        user.save(using=self._db)
        return user

    def create_user(self, phone_number, password, **extra_fields):
        user = self._create_user(phone_number, password, False, False, **extra_fields)
        user.save(using=self._db)
        return user

    def create_superuser(self, phone_number, password, **extra_fields):
        user = self._create_user(phone_number, password, True, True, **extra_fields)
        user.username = f"admin-{user.id}"
        user.save(using=self._db)
        return user

    def get_by_natural_key(self, phone_number):
        return self.get(phone_number=phone_number)

class User(AbstractUser):
    username = models.CharField(max_length=30, null=True)
    phone_number = models.CharField(max_length=20, unique=True)
    objects = UserManager()

    USERNAME_FIELD = "phone_number"
    REQUIRED_FIELDS = []

    def __str__(self):
        return f"{self.pk} {self.phone_number}"

    class Meta:
        db_table = "User"

myapp/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic import TemplateView
from rest_framework.views import APIView

# Create your views here.

def hello_world(request):
    return HttpResponse("<h1>Hello world</h1>")

class FirstView(TemplateView):
    template_name = 'myapp/first.html'

class SecondView(APIView):
    def get(self,request):
        user = "wpdnr"
        return render(request, "myapp/second.html",{"user" : user})

todo/views.py
from django.shortcuts import render
from rest_framework.views import APIView
from .models import Todo

# Create your views here.

class TodoCreateView(APIView):
    def get(self, request):
        return render(request, "todo/create.html",{})


class TodoListView(APIView):
    def get(self, request):
        todo_list = Todo.objects.all()
        return render(request, "todo/list.html", {"todo_list" : todo_list})


class TodoDetailView(APIView):
    def get(self, request,pk):
        todo = Todo.objects.filter(id = pk).first()
        return render(request, "todo/detail.html", {"todo": todo})


class TodoUpdateView(APIView):
    def get(self, request,pk):
        todo = Todo.objects.filter(id=pk).first()
        return render(request, "todo/update.html", {"todo": todo})

users/views.py
from django.shortcuts import render
from rest_framework.views import APIView

# Create your views here.
class SignupView(APIView):
    def get(self, request):
        return render(request, "users/signup.html")


class LoginView(APIView):
    def get(self, request):
        return render(request, "users/login.html")

templates/base.html
<!doctype html>
<html lang="en">
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- jQuery -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

  <style>
    .todowrap{display: flex; justify-content: center; align-items: center;}
    .todowrap .box{box-shadow: 1em 0 2em rgb(0 0 0 / 20%); border-radius: 5px; padding: 30px;}
    .todowrap .box h2{font-weight: 100;   text-align: center; margin-bottom: 3rem;}
    .todowrap .box #title{ width: 95%; border: 1px solid #222; padding:10px; border-radius: 5px;}
    .box div{display: flex;}
    .sm-box p{margin-right: 2rem;}
    textarea{width: 95%;padding:10px; height: 6.25em;resize: none; margin-top: 2rem; border-radius: 5px;}
    button{width:120px;height: 40px;color:#fff;background: #004fff;font-size: 16px;border:none;border-radius: 20px;cursor: pointer;}
    .btn-box{justify-content: end;}

    .des_wrap{padding:10px; background: #d9d9d97d; border-radius:5px; margin-bottom:2rem;}
    #delete-btn { background: #E40F18;}
    .list_title{background: #d9d9d97d; border-radius: 5px;padding: 9px;}

    .listbox{
      display: flex;
      flex-direction: row;
      width: 350px;
      border-bottom: 1px solid #456EFE;
      margin-bottom: 1.3rem;
  }
  .listbox a{color: black;  margin-bottom: 0.5rem;font-size:16px;text-decoration-line: none;}
  </style>

</head>

<body class="todowrap">

{% block content %}
{% endblock %}

</body>


</html>

templates/myapp/first.html
<h3>first page !</h3>

templates/myapp/second.html
<h3>second page !</h3>
<h3>welcome {{ user }} django Templaete Variable</h3>

templates/todo/create.html
{% extends 'base.html' %}

{% block content %}


    <div class="box">
        <h2>Todo Create Page</h2>
        <input type="text" id="title" placeholder="Title...">
        <textarea  id="description" placeholder="Description..."></textarea>

        <div class="sm-box">
            <input type="checkbox" id="complete">
            <p>complete</p>

            <input type="checkbox" id="important">
            <p>important</p>
        </div>

        <div class="btn-box">
            <button type="submit" id="submit">submit</button>
        </div>

    </div>

<script>

      // 버튼 눌렀을 때
      $('#submit').click(function () {

          let title = $('#title').val();
          let description = $('#description').val();
          let complete = $('#complete').is(":checked");
          let important = $('#important').is(":checked");

            console.log(title);

            $.ajax({
                url: "/todo/api/create/",
                data: {
                    title:title,
                    description:description,
                    complete:complete,
                    important:important,
                },
                method: "POST",
                success: function (data){
                    alert("Todo 생성 성공!");
                },
                error:function (request, status, error){
                    alert("Todo 생성 실패!");
                },
                complete: function (data) {
                    location.replace("/todo/list/");
                },
            });
      });

</script>


{% endblock %}

templates/todo/detail.html
{% extends 'base.html' %}

{% block content %}

<div class="box">


    <a href="{% url 'todo:list' %}" style="color:#a19c9c;">back</a>

    <h2>Todo Detail Page</h2>

    {% if todo %}

        <p class="list_title">{{todo.title}}</p>
        <div class="des_wrap">
            <p>{{todo.description}}</p>
        </div>



    <div style="display: flex; flex-direction: row;">
        <a href="{% url 'todo:update' pk=todo.id %}">
            <button type="submit">edit</button>
        </a>

        <div class="btn-box" style="margin-left:1rem;">
            <button type="submit" id="delete-btn">delete</button>
        </div>

    </div>

</div>

{% endif %}

<script>
// 버튼 눌렀을 때
      $('#delete-btn').click(function () {

            $.ajax({
                url: "/todo/api/delete/{{todo.id}}",
                data: {

                },
                method: "DELETE",
                success: function (data){
                    alert("Todo 삭제 성공!");
                },
                error:function (request, status, error){
                    alert("Todo 삭제 실패!");
                },
                complete: function (data) {
                    location.replace("/todo/list")
                },
            });
      });

</script>




{% endblock %}

templates/todo/list.html
{% extends 'base.html' %}

{% block content %}

<div class="box">

    <h2>Todo List Page</h2>

    {% for todo in todo_list %}

    <div class="listbox">
        <a href="{% url 'todo:detail' pk=todo.id %}">
            {{todo.title}}
        </a>
    </div>

    {% endfor %}


    <div class="btn-box">
        <button type="submit" id="create-btn" onclick="location.replace('/todo/create/')">create</button>
    </div>

</div>



{% endblock %}

templates/todo/update.html
{% extends 'base.html' %}

{% block content %}

<div class="box">
    <h2>Todo Update Page</h2>
    <input type="text" id="title" placeholder="Title..." value="{{todo.title}}">
    <textarea id="description" placeholder="Description...">{{todo.description}}</textarea>

    <div class="sm-box">
        {% if todo.complete == 1%}
            <input type="checkbox" id="complete" checked>
        {% else %}
            <input type="checkbox" id="complete">
        {% endif %}
        <p>complete</p>

        {% if todo.important == 1%}
            <input type="checkbox" id="important" checked>
        {% else %}
            <input type="checkbox" id="important">
        {% endif %}
        <p>important</p>
    </div>


    <div class="btn-box">
        <button type="submit" id="submit">update</button>
    </div>
</div>

<script>

    $( document ).ready(function() {
        console.log();

    });

      // 버튼 눌렀을 때
      $('#submit').click(function () {

          let title = $('#title').val();
          let description = $('#description').val();
          let complete = $('#complete').is(":checked");
          let important = $('#important').is(":checked");

            $.ajax({
                url: "/todo/api/update/{{todo.id}}",
                data: {
                    title:title,
                    description:description,
                    complete:complete,
                    important:important,
                },
                method: "PATCH",
                success: function (data){
                    alert("Todo 수정 성공!");
                    location.replace("/todo/detail/{{todo.id}}")
                },
                error:function (request, status, error){
                    alert("Todo 수정 실패!");
                },
                complete: function (data) {
                    //console.log("완료");
                },
            });
      });

</script>


{% endblock %}